### ISSUE TITLE
Bug in AndNot

### ISSUE THREAD

**Issue by ebonetti** [tgruben/roaring#29]
Sometimes the function "AndNot" shows a bug: on a big set and a subset "roaring.AndNot(subset, set)" is not empty, but it should be.

The code and the sets are in the 7zip file at:
https://drive.google.com/file/d/0B7aIxjl31WjSOGVVTE5YNzRuTzA/view?usp=sharing

Keep up the good work,
Enrico

**Comment by lemire** [comment]
Thanks. This will get investigated shortly.

**Comment by lemire** [comment]
@ebonetti 

Thanks for catching this issue. Fixed by this commit:

https://github.com/tgruben/roaring/commit/55ec56cc331976da5edf31c183ec928d267352c9

I am closing the issue, please reopen if you disagree.
